def imagesList = ["test", "acc", "dev", "cypress"]
def tagList = ["latest", "timestamp"]

@NonCPS
def getAllImages(rootPath) {
    def list = []
    for (subPath in rootPath.list()) {
        list << subPath.getName()
        // in case you don't want extension
        // list << FilenameUtils.removeExtension(subPath.getName())
    }
    return list
}

pipeline {
    agent any



    stages {
        stage('Checkout code') {
            steps {
                checkout scm
                files = findFiles(glob: 'containers')
            }
        }
        stage('Select image to build') {
            steps {
                script {
                    env = input message: "Select image (Dockerfile)",
                        parameters: [
                            choice(name: "image", choices: imagesList, description: "specifieert de namespace binnen de Atos Openshift cluster.")
                        ]
                }
                // echo 'Please select a tag'
            }
        }
        stage('Build and push to nexus') {
            steps {
                echo 'Kaniko: building and pushing ...'
            }
        }
    }
}
