def registry = "http://nexus"
def dirPath = "containers"
def imagesList = []
def tagList = ["latest", "timestamp"]

def getImagesList(dir) {
    sh "ls ${dir} > _list"
    def list = readFile( "_list" ).split( "\\r?\\n" ) as List;
    sh "rm -f _list"
    return list
}

pipeline {
    agent any

    stages {
        stage('Checkout code') {
            steps {
                checkout scm
            }
        }
        stage('Select image and tag to build') {
            steps {
                script {
                    imagesList = getImagesList(dirPath)
                    image = input message: "Select image (Dockerfile)", parameters: [choice(name: "image", choices: imagesList)]
                    tag = input message: "Select tag (latest)", parameters: [choice(name: "tag", choices: tagList)]
                }
                // echo 'Please select a tag'
            }
        }
        stage('Build and push to nexus') {
            steps {
                script {
                    // ${BUILD_TIMESTAMP}
                    tag = tag !== 'timestamp' ? tag : new Date().getTime()/1000 as Integer 
                    echo "Kaniko: building and pushing image: ${registry}/${image}:${tag} ... to Nexus"
                }
                
            }
        }
    }
}
